### PR TITLE
New Lock-Icons to display locked factions

### PR DESCRIPTION
**Pull request by ghost**
This is the logic for the lock-icons. The new icons should be added to master branch soon. They were separated for readability. PR#68 is the design aspect, PR$66 is the logic aspect.

### CODE REVIEW

**Comment by sarahsturgeon** [comment]
Can one of the admins verify this patch?

**Comment by ghost** [comment]
Locked/Unlocked icon takes up cell's width. Needs to be looked into before final merge.

**Comment by ghost** [comment]
This still needs to be looked into to make the new icons sized properly. They currently still take up the width of the cell in DListView.

**Comment by ghost** [comment]
On hold till I can get a clientside cleanup finished and running. Should be fixed when that happens

**Pull request closed without merging**
